name: "release"

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: 'stable'
      - uses: actions/checkout@master
      - run: cargo build --release
      - run: cargo publish --token ${{ env.CARGO_TOKEN }}
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
